language: python
python:
  - "2.7"
install:
  - "pip install --upgrade setuptools pip"
  - "pip install -r -U requirements.txt"
  - "pip install -r -U dev-requirements.txt"
script:
  - "py.test"
after_success:
  - "coveralls"
notifications:
  email: false
sudo: false
